"""MonitoringService implementation for API Observability."""

import logging
from typing import Any

from src.api.observability.pipeline import ObservabilityPipeline
from src.api.observability.telemetry_models import (
    ApiOperationalSnapshot,
    ObservationEvent,
    RequestMetrics,
    RequestTrace,
)

logger = logging.getLogger("arbiter.api.observability")


class MonitoringService:
    """Coordinates API Observability execution.

    Responsibilities:
    - Receive ObservationEvent payloads from transport/middleware
    - Pass ObservationEvents through ObservabilityPipeline safely
    - Expose current RequestMetrics and ApiOperationalSnapshot summaries
    - Ensure zero side-effects on primary request handling
    """

    def __init__(self, pipeline: ObservabilityPipeline) -> None:
        self._pipeline = pipeline

    def process_observation(self, event: ObservationEvent) -> None:
        """Processes an ObservationEvent through the ObservabilityPipeline safely."""
        self._pipeline.execute(event)

    def get_current_metrics(self) -> RequestMetrics:
        """Returns the current aggregated request metrics."""
        return self._pipeline.get_metrics()

    def get_latest_snapshot(self) -> ApiOperationalSnapshot | None:
        """Returns the latest operational snapshot generated by the pipeline."""
        return self._pipeline.get_latest_snapshot()

    def get_latest_trace(self) -> RequestTrace | None:
        """Returns the latest generated request trace."""
        return self._pipeline.get_latest_trace()

    def get_health_metrics(self) -> dict[str, Any]:
        """Exposes health metrics dictionary suitable for health endpoints."""
        metrics = self.get_current_metrics()
        snapshot = self.get_latest_snapshot()
        status = snapshot.system_status if snapshot else "HEALTHY"
        return {
            "status": status,
            "total_requests": metrics.total_requests,
            "successful_requests": metrics.successful_requests,
            "failed_requests": metrics.failed_requests,
            "error_rate": metrics.error_rate,
            "avg_latency_ms": metrics.avg_latency_ms,
            "p95_latency_ms": metrics.p95_latency_ms,
        }
