"""Immutable data models for API Observability, Telemetry & Monitoring."""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ObservationEvent(BaseModel):
    """Immutable event payload consumed by observability components."""

    model_config = ConfigDict(frozen=True)

    event_id: str
    timestamp_ns: int
    correlation_id: str
    route_path: str
    http_method: str
    status_code: int
    duration_ns: int
    request_bytes: int = Field(default=0, ge=0)
    response_bytes: int = Field(default=0, ge=0)
    error_code: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class ApiTelemetryEvent(BaseModel):
    """Immutable telemetry event produced by the TelemetryCollector."""

    model_config = ConfigDict(frozen=True)

    telemetry_id: str
    observation_event: ObservationEvent
    collected_at_ns: int
    tags: tuple[str, ...] = Field(default_factory=tuple)


class RequestTrace(BaseModel):
    """Immutable distributed trace payload produced by the TracingProvider."""

    model_config = ConfigDict(frozen=True)

    trace_id: str
    parent_span_id: str | None = None
    span_id: str
    correlation_id: str
    start_time_ns: int
    end_time_ns: int
    attributes: dict[str, Any] = Field(default_factory=dict)


class RequestMetrics(BaseModel):
    """Immutable metrics calculation computed by the MetricsAggregator."""

    model_config = ConfigDict(frozen=True)

    total_requests: int = Field(default=0, ge=0)
    successful_requests: int = Field(default=0, ge=0)
    failed_requests: int = Field(default=0, ge=0)
    error_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_latency_ms: float = Field(default=0.0, ge=0.0)
    p95_latency_ms: float = Field(default=0.0, ge=0.0)
    p99_latency_ms: float = Field(default=0.0, ge=0.0)
    requests_per_second: float = Field(default=0.0, ge=0.0)
    status_code_counts: dict[int, int] = Field(default_factory=dict)


class ApiOperationalSnapshot(BaseModel):
    """Immutable operational snapshot generated by SnapshotGenerator."""

    model_config = ConfigDict(frozen=True)

    snapshot_id: str
    timestamp_ns: int
    active_profile_id: str
    metrics: RequestMetrics
    system_status: str = "HEALTHY"
    active_collectors: tuple[str, ...] = Field(default_factory=tuple)
    metadata: dict[str, Any] = Field(default_factory=dict)


class MonitoringProfile(BaseModel):
    """Immutable profile configuration for observability."""

    model_config = ConfigDict(frozen=True)

    profile_id: str
    enabled_collectors: tuple[str, ...] = Field(
        default_factory=lambda: ("default_collector",)
    )
    enabled_tracing_provider: str = "default_tracing"
    enabled_metrics_aggregators: tuple[str, ...] = Field(
        default_factory=lambda: ("default_aggregator",)
    )
    snapshot_interval_seconds: float = Field(default=60.0, gt=0.0)
    sampling_configuration: dict[str, Any] = Field(
        default_factory=lambda: {"sampling_rate": 1.0}
    )


class TelemetryCollectionResult(BaseModel):
    """Immutable result wrapper returned by telemetry collection operations."""

    model_config = ConfigDict(frozen=True)

    event_id: str
    success: bool
    collected_event: ApiTelemetryEvent | None = None
    error_message: str | None = None
