"""Verification subsystem for Arbiter."""

from src.core.verification.aggregation import (
    BaseAggregationStrategy,
    MaxConfidenceAggregationStrategy,
)
from src.core.verification.base import BaseMetadataProvider, BaseNLIModel, BaseVerifier
from src.core.verification.implementations import DefaultMetadataProvider, NLIVerifier
from src.core.verification.verification_models import (
    AggregationMetadata,
    ClaimVerificationContext,
    ClaimVerificationInput,
    ExecutionDevice,
    NLILabelSchema,
    NLIModelDefinition,
    NLIVerificationDefinition,
    PassageVerificationInput,
    PassageVerificationMetadata,
    PassageVerificationResult,
    PassageVerificationScore,
    ProbabilitySchema,
    VerificationDefinition,
    VerificationExecutionMetadata,
    VerificationExplanation,
    VerificationLabel,
    VerificationMetadata,
    VerificationModelMetadata,
    VerificationProfile,
    VerificationProfileRegistry,
    VerificationResult,
    VerificationVerdict,
    VerifiedPassage,
    VerifierRuntimeMetadata,
)

__all__ = [
    "BaseAggregationStrategy",
    "BaseVerifier",
    "BaseNLIModel",
    "BaseMetadataProvider",
    "DefaultMetadataProvider",
    "MaxConfidenceAggregationStrategy",
    "NLIVerificationDefinition",
    "NLIVerifier",
    "ExecutionDevice",
    "NLILabelSchema",
    "NLIModelDefinition",
    "ProbabilitySchema",
    "PassageVerificationScore",
    "PassageVerificationMetadata",
    "PassageVerificationResult",
    "PassageVerificationInput",
    "ClaimVerificationInput",
    "AggregationMetadata",
    "ClaimVerificationContext",
    "VerifierRuntimeMetadata",
    "VerificationExecutionMetadata",
    "VerificationDefinition",
    "VerificationExplanation",
    "VerificationLabel",
    "VerificationMetadata",
    "VerificationModelMetadata",
    "VerificationProfile",
    "VerificationProfileRegistry",
    "VerificationResult",
    "VerificationVerdict",
    "VerifiedPassage",
]
